# NOTE: update this with your service name
service: chuckNorrisVoice

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-offline-scheduler
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-iam-roles-per-function
  - serverless-plugin-offline-dynamodb-stream

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2

  environment:
    AWS_ACC_KEY_ID: ${env:AWS_ACC_KEY_ID}
    AWS_SECRET: ${env:AWS_SECRET}
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - dynamodb:DescribeTable
  #       - dynamodb:Query
  #       - dynamodb:Scan
  #       - dynamodb:GetItem
  #       - dynamodb:PutItem
  #       - dynamodb:UpdateItem
  #       - dynamodb:DeleteItem
  #     Resource: "arn:aws:dynamodb:ap-southeast-2:019137212646:table/chuckNorrisJokes"
custom:
  serverless-offline-dynamodb-streams:
    apiVersion: "2013-12-02"
    endpoint: http://0.0.0.0:8000
    region: ap-south-east-2
    accessKeyId: ${env:AWS_ACC_KEY_ID}
    secretAccessKey: ${env:AWS_SECRET}
    skipCacheInvalidation: false
    readInterval: 500

functions:
  mainWorker:
    handler: handler.mainWorker
    events:
      - stream:
          enabled: true
          type: dynamodb
          arn: arn:aws:dynamodb:ap-southeast-2:019137212646:table/chuckNorrisJokes/stream/2020-05-11T01:07:58.471
          batchSize: 10
          startingPosition: TRIM_HORIZON

  joke:
    handler: handler.joke
    iamRoleStatements:
      - Effect: Allow
        Action:
          #- dynamodb:DescribeTable
          #- dynamodb:Query
          #- dynamodb:Scan
          #- dynamodb:GetItem
          - dynamodb:PutItem
          #- dynamodb:UpdateItem
          #- dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:ap-southeast-2:019137212646:table/chuckNorrisJokes"
    events:
      - schedule: rate(1 minute)
